name: Relative Color Palette
sorting: 46
new: 1
mdn: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors
data:
    colors:
        - '#0055cc'
        - '#5e4db2'
        - '#abdced'
        - '#247554'
        - '#c6398f'
        - '#ffcc33'
        - '#ee6d11'
        - '#d13a2e'
        - '#000000'
        - '#ffffff'
    percentages:
        - '100%'
        - '95%'
        - '90%'
        - '85%'
        - '80%'
        - '75%'
        - '70%'
        - '65%'
        - '60%'
        - '55%'
        - '50%'
        - '45%'
        - '40%'
        - '35%'
        - '30%'
        - '25%'
        - '20%'
        - '15%'
        - '10%'
        - '5%'
        - '0%'
    spaces:
        - hsl
        - lch
        - oklch
        - lab
        - oklab
