name: Color Palette
sorting: 43
data:
    colors:
        - '#0055cc'
        - '#5e4db2'
        - '#abdced'
        - '#247554'
        - '#c6398f'
        - '#ffcc33'
        - '#ee6d11'
        - '#d13a2e'
        - '#000000'
        - '#ffffff'
    percentages:
        - '100%'
        - '90%'
        - '80%'
        - '70%'
        - '60%'
        - '50%'
        - '40%'
        - '30%'
        - '20%'
        - '10%'
        - '0%'
    spaces:
        - srgb
        - srgb-linear
        - hsl
        - hwb
        - lch
        - oklch
        - lab
        - oklab
