name: Color Palette
sorting: 43
data:
    colors:
        - '#0d6efd'
        - '#6610f2'
        - '#6f42c1'
        - '#d63384'
        - '#dc3545'
        - '#fd7e14'
        - '#ffc107'
        - '#198754'
        - '#20c997'
        - '#0dcaf0'
        - '#000000'
        - '#ffffff'
    percentages:
        - '100%'
        - '90%'
        - '80%'
        - '70%'
        - '60%'
        - '50%'
        - '40%'
        - '30%'
        - '20%'
        - '10%'
        - '0%'
    spaces:
        - srgb
        - srgb-linear
        - hsl
        - hwb
        - lch
        - oklch
        - lab
        - oklab
