name: Color Mix Mixer
sorting: 43
features: color-mix
data:
    colorA: '#00aaff'
    colorB: '#ffaa00'
    spaces:
        - srgb
        - hsl
        - lch
        - oklch
        - lab
        - oklab
