name: Color Mix Mixer
sorting: 43
mdn: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix
data:
    colorA: '#00aaff'
    colorB: '#ffaa00'
    spaces:
        - srgb
        - hsl
        - lch
        - oklch
        - lab
        - oklab
