name: Relative Color
sorting: 45
new: true
mdn: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors
data:
    percentages:
        - '100%'
        - '95%'
        - '90%'
        - '85%'
        - '80%'
        - '75%'
        - '70%'
        - '65%'
        - '60%'
        - '55%'
        - '50%'
        - '45%'
        - '40%'
        - '35%'
        - '30%'
        - '25%'
        - '20%'
        - '15%'
        - '10%'
        - '5%'
        - '0%'
    spaces:
        - hsl
        - lch
        - oklch
        - lab
        - oklab
