name: Relative Color
sorting: 45
features: relative-color
data:
    percentages:
        - '100%'
        - '95%'
        - '90%'
        - '85%'
        - '80%'
        - '75%'
        - '70%'
        - '65%'
        - '60%'
        - '55%'
        - '50%'
        - '45%'
        - '40%'
        - '35%'
        - '30%'
        - '25%'
        - '20%'
        - '15%'
        - '10%'
        - '5%'
        - '0%'
    spaces:
        - hsl
        - lch
        - oklch
        - lab
        - oklab
