name: Container Style Queries
sorting: 21
source: https://developer.chrome.com/blog/style-queries/
data:
    products:
        -
            name: Spring Jacket
            image: /assets/images/jackets/black.jpeg
            season: spring
            status: old
        -
            name: Summer Jacket
            image: /assets/images/jackets/blue.jpeg
            season: summer
            status: current
        -
            name: Autumn Jacket
            image: /assets/images/jackets/green.jpeg
            season: autumn
            status: new
        -
            name: Winter Jacket
            image: /assets/images/jackets/yellow.jpeg
            season: winter
            status: next
