name: deploy

on:
  push:
    branches: [master]

concurrency: production_environment

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://modern-css-demos.bk2k.info
    if: (github.repository == 'benjaminkott/moderncss-demos')
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download Deployer
        run: |
          curl -LO https://github.com/deployphp/deployer/releases/download/v7.4.0/deployer.phar
          sudo mv deployer.phar /usr/local/bin/dep;
          sudo chmod +x /usr/local/bin/dep;

      - name: Build PHP
        run: composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader

      - name: Build Frontend
        run: npm install && npm run build

      - name: Setup SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh-auth.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_rsa
          chmod 0600 ~/.ssh/deploy_rsa
          ssh-keygen -p -P "${{ secrets.SSH_PASSPHRASE }}" -N "" -f ~/.ssh/deploy_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/deploy_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_AUTH_SOCK: /tmp/ssh-auth.sock
        run: |
          dep deploy;
